/*
    Snake has dummy data as 'state'.
    SnakeMouth get newData by form, input
    SnakeTail render <div> according to data from Snake
*/

import { useState } from "react";
import SnakeMouth from "./SnakeMouth";
import SnakeTail from "./SnakeTail";

/**
 * @returns container contains form and divs
 * - form generate inputs by Object.keys(data[0]).
 * - divs generated by length of data array.
 */
const Snake = () => {
    const [data, setData] = useState([
        {
            key: 1,
            id: 'apple',
            pw:  'aaa',
            test: 'kkk',
          },
          {
            key: 2,
            id: 'banana',
            pw: 'bbb'
          },
          {
            key: 3,
            id: 'orange',
            pw: 'ccc'
          },
    ]);

    const saveDataHandler = (newData) => {
        console.log('saveDataHandler', newData);
        setData((prevData) => {
            return [
                newData,
                ...prevData
            ];
        });
    };

    return (
        <div className="snake-container">
            <SnakeMouth keys={Object.keys(data[0])} onSaveData={saveDataHandler}></SnakeMouth>
            <SnakeTail data={data} />
        </div>
    );
}

export default Snake;